export const names = [
  "Joy",
  "Alex",
  "Paul",
  "Ifeoma",
  "Precious",
  "Henry",
  "Anie",
  "Kate",
  "Alice",
  "Bob",
  "Charlie",
  "David",
  "Eva",
  "Frank",
  "Grace",
  "Hannah",
  "Ian",
  "Jane",
  "Karl",
  "Laura",
  "Mike",
  "Nina",
  "Oscar",
  "Paula",
  "Quinn",
  "Rachel",
  "Sam",
  "Tina",
  "Uma",
  "Victor",
  "Wendy",
  "Xander",
  "Yara",
  "Zane",
  "Adrian",
  "Bella",
  "Cameron",
  "Diana",
  "Evan",
  "Fiona",
  "George",
  "Harriet",
  "Isaac",
  "Jill",
  "Kevin",
  "Liam",
  "Mia",
  "Noah",
  "Olivia",
  "Peter",
  "Quincy",
  "Rebecca",
  "Steven",
  "Tracy",
  "Ulysses",
  "Vivian",
  "William",
];

export const randomNumbers = [
  45, 78, 12, 33, 90, 56, 67, 23, 88, 100, 55, 43, 21, 72, 60, 39, 81, 92, 34,
  59, 28, 97, 74, 41, 63, 19, 86, 52, 79, 13, 31, 66, 24, 77, 99, 15, 82, 46,
  37, 65, 91, 48, 25, 73, 84, 18, 50, 29, 61, 98,
];

export const people = [
  {
    firstName: "John",
    lastName: "Doe",
    age: 25,
    occupation: "Engineer",
    hobbies: ["reading", "hiking", "gaming"],
    country: "USA",
    state: "California",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    favoriteFood: "Pizza",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    age: 30,
    occupation: "Designer",
    hobbies: ["painting", "yoga", "traveling"],
    country: "USA",
    state: "New York",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    favoriteFood: "Sushi",
  },
  {
    firstName: "Emily",
    lastName: "Johnson",
    age: 22,
    occupation: "Student",
    hobbies: ["reading", "dancing", "swimming"],
    country: "Canada",
    state: "Ontario",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    favoriteFood: "Pasta",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    age: 40,
    occupation: "Chef",
    hobbies: ["cooking", "biking", "gardening"],
    country: "UK",
    state: "London",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    favoriteFood: "Steak",
  },
  {
    firstName: "Anna",
    lastName: "Williams",
    age: 28,
    occupation: "Nurse",
    hobbies: ["running", "reading", "cooking"],
    country: "Australia",
    state: "Victoria",
    gender: "Female",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    favoriteFood: "Salad",
  },
  {
    firstName: "Chris",
    lastName: "Davis",
    age: 35,
    occupation: "Teacher",
    hobbies: ["cycling", "photography", "traveling"],
    country: "USA",
    state: "Texas",
    gender: "Male",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    favoriteFood: "Burger",
  },
];
